server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:productsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html